### ISSUE TITLE
PermissionService missing isValid() method referenced by PermissionPolicy

### ISSUE THREAD

**Issue by tzaffi** [tjwebb/sails-permissions#11]
I'm trying to implement a Sails project using **sails-permissions / sails-auth**. 

It appears that `/api/services/PermissionServices.js` is incomplete as `/api/policies/PermissionPolicy` references `PermissionService.isValid()` on line 46, while no such method exists in `PermissionService.js`.

**Comment by tjwebb** [comment]
Strange, I'll try to see why that is.

**Comment by tjwebb** [comment]
I've significantly overhauled sails-permissions in the past few weeks. Go ahead and try it out if you're still interested.

**Comment by tzaffi** [comment]
Great. I will try out the new code. If the need arises, I'll create a new issue.
