### ISSUE TITLE
Sails-Permissions not adhering to owner relation permission, individual records accessible by all users

### ISSUE THREAD

**Issue by jBlack87** [tjwebb/sails-permissions#116]
It looks like in the OwnerPolicy, the createdby attribute is set to the id of the authenticated user, and i can confirm that the request is getting updated to the correct ID, but when i try to load records that the user has access to ( the user only has read access to records it created ) I get zero results and createdBy isn't set at all.

I may be missing something here, or is that attribute in the OwnerPolicy being lost somewhere down the line?

**Comment by jBlack87** [comment]
Update: I have determined the createdBy attribute wasn't being set due to my sails configuration. I setup a test project with fresh copy of sails, and sails-permissions. It seems that what I want to do specifically, doesn't work. 

I want users with role "registered" to be able to create new records for "review" model, and only be able to "read" review records created by themselves. I've set the relation for read action to owner, but the result is that review records created by userA are not visible when navigating to /review but if I navigate to /review/1 any user can access individual records, this seems like a breaking bug to me??

I've tried sails-permissions 1.3.6 and then rolled back to 1.3.1 to compare, same problem persists back to 1.3.1

I only ran 2 permission grant commands on the registered role:

PermissionService.grant({action: 'read', model: 'review', role: 'registered', relation:'owner'}) 
PermissionService.grant({action: 'create', model: 'review', role: 'registered'}) 
 

Am I doing something severely wrong, or is there a flaw in sails-permissions not adhering to owner relation?

**Comment by jBlack87** [comment]
PR #118 seems to fix my problem with the owner not working, and as far as I can tell it really has to be set server side but isn't. 

I'm also finding it odd that findRecords seems to always return objects when you pass an id of that record, ignoring permissions and owner relation entirely.

**Comment by ryanwilliamquinn** [comment]
@jBlack87 Are you sure those are the only roles related to reading that model?

**Comment by ryanwilliamquinn** [comment]
Regarding ownership, it is not an accident that ownership is not set accidentally.  The creator of the object may not be the owner.  You can manually set the `owner` property when you create a model instance.

**Comment by jBlack87** [comment]
ah, so your saying that the proper way to do this is to set owner per model? I guess in my case I wanted it across all models so I hadn't considered that. Thanks! For the single record permission issue, I am just double checking, but I did try it on a fresh install of sails and sails-permissions and it was my understanding that the registered role started with no permissions aside form User model and "Model" model?

**Comment by tjwebb** [comment]
The possible creator != owner situation is very real, but might also just be a result of me trying to be overly-pedantic in my design. Permissioning is necessarily detail-driven, but I'm open to reconsidering this decision if it's causing confusion. @jBlack87 what are your thoughts?

**Comment by jBlack87** [comment]
My take on this is that while create != owner  is pretty common, an "out of the box" expectation would be that the owner is set to the user sending the post request, and could then be changed if need be.
