### ISSUE TITLE
Error: Cannot find module 'lodash' installing on a new sails app.

### ISSUE THREAD

**Issue by ksylvan** [tjwebb/sails-permissions#117]
I created a new Sails application, followed the Quick Start instructions in the README.md and I see this on "sails lift":

    info: Starting app...
    
    module.js:338
        throw err;
        ^
    Error: Cannot find module 'lodash'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.Module._load (module.js:278:25)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)

Info on my installation:

    $ sails -v
    0.11.0
    $ grep sails package.json 
        "grunt-sails-linker": "~0.9.5",
        "sails": "~0.11.0",
        "sails-auth": "^1.3.1",
        "sails-disk": "~0.10.0",
        "sails-permissions": "^1.3.6",
        "sails-redis": "^0.10.4"

After "npm install --save lodash" it works. However, each subsequent "sails lift" gives me an error about trying to insert the admin user every time:

    Error: Error (E_UNKNOWN) :: Encountered an unexpected error
    AdapterError: Record does not satisfy unique constraints

Looks like the application lifts, now I am trying to figure out how to use the /auth/local endpoint. Thanks for creating this!

**Comment by tjwebb** [comment]
What db adapter are you using?

**Comment by ksylvan** [comment]
I'm using 'sails-redis'

**Comment by ksylvan** [comment]
Created a new issue for the sails-redis adapter problem.

https://github.com/tjwebb/sails-permissions/issues/121

Closing this one.
