### ISSUE TITLE
Error in PermissionService.addUsersToRole

### ISSUE THREAD

**Issue by redBaronNc** [tjwebb/sails-permissions#120]
Hello,
I have found a problem causing some errors in when adding a role to users.
at line 282 of PermissionService.js you use :
role.users.add(_.pluck(users, 'id'));
the problem is that the add function does'nt take arrays as parameter.
You have to look in the array and call add several times instead.
This solved the error I was having:

  addUsersToRole: function (usernames, rolename) {
    if (_.isEmpty(usernames)) {
       return Promise.reject(new Error('One or more usernames must be provided'));
    }

    if (!_.isArray(usernames)) {
        usernames = [usernames];
    }

    return Role.findOne({name: rolename}).populate('users').then(function (role) {
        return User.find({username: usernames}).then(function (users) {
            sails.log(users);
            //role.users.add(_.pluck(users, 'id'));
            for(var i in users){
              role.users.add(users[i].id);
            }
            return role.save();
        }).catch(function(err){
          sails.log.error('Finding user');
          sails.log.error(err);});
    }).catch(function(err){
      sails.log.error('Finding role');
      sails.log.error(err);});
  },

Error message:
error: [ { type: 'insert',
    collection: 'user',
    values: [ 39 ],
    err: 'Invalid valuesList specified (should be an array of valid values objects!)\n==============================================\nProper usage :: \nUser.createEach(valuesList, callback)\n==============================================\n' } ]

I hope it helps :-)

**Comment by ryanwilliamquinn** [comment]
Thanks for pointing that out.  If you have a pull request, that would be great, otherwise I can take care of it.

**Comment by ryanwilliamquinn** [comment]
https://github.com/tjwebb/sails-permissions/pull/153
