### ISSUE TITLE
apparent logic error?

### ISSUE THREAD

**Issue by tjwebb** [tjwebb/sails-permissions#122]
https://github.com/tjwebb/sails-permissions/blob/master/api/policies/RolePolicy.js#L37

@ryanwilliamquinn where does `objects` come from? That looks like it can't possibly work. Sanity check is appreciated when you get a chance.

**Comment by ryanwilliamquinn** [comment]
Looks like a bad merge, I will try to patch it back together.

**Comment by ryanwilliamquinn** [comment]
This was resolved in 1.4.3
