### ISSUE TITLE
How to remove default roles and permissions?

### ISSUE THREAD

**Issue by Sriram-27727** [tjwebb/sails-permissions#131]
I just want create custom roles and permissions ans remove default roles and permissions. If anyone knows pls help me

**Comment by ryanwilliamquinn** [comment]
You can delete all the roles and permissions from the database, or via the sails console, and create new ones.

via sails console:
```
Role.destroy({}, console.log)
Permission.destroy({}, console.log)
```

**Comment by Sriram-27727** [comment]
Thank you ryanwilliamquinn.
