### ISSUE TITLE
PUT Rest API does not seem to work.

### ISSUE THREAD

**Issue by ksylvan** [tjwebb/sails-permissions#132]
From the documentatoin:

"With sails-permissions, new Users should only be created through the sails.js REST API, e.g.

    POST /user
    {
      username: 'tjwebb',
      email: 'me@traviswebb.com',
      password: 'test1234'
    }

And I managed to create a new user ("kayvan") via POST to /user (while authenticated as admin).

    sails> User.findByUsername('kayvan').then(console.log)
    sails> [ { createdBy: 1,
        owner: 3,
        username: 'kayvan',
        email: 'kayvansylvan@gmail.com',
        createdAt: '2015-08-27T00:02:43.280Z',
        updatedAt: '2015-08-27T00:02:43.316Z',
        id: 3 } ]

The REST API for modifying a user would be to PUT to /:model/:record (e.g.) for my case, PUT to /user/3, so I do:

    PUT /user/3
    {
        password: 'secretpassword'
    }

While authenticated as "admin" and I get a 404 response.

When I do the same with PUT to /user/1, the PUT succeeds, but the passport password does not change, instead, I get a new field added to the User record:

    [ { createdBy: 1,
    owner: 1,
    username: 'admin',
    email: 'kayvan.sylvan@disney.com',
    model: 5,
    createdAt: '2015-08-23T07:24:42.986Z',
    updatedAt: '2015-08-27T00:14:03.665Z',
    id: 1,
    password: 'secretpassword' } ]

There are two issues here:

1) Why isn't the admin user authorized to PUT on some other user record?

2) What is the right way for me to change a user password? (or the admin password) within the app?

Thanks!

**Comment by ryanwilliamquinn** [comment]
1) Why isn't the admin user authorized to PUT on some other user record?
I was able to PUT on different user records with an admin user without issue, I'm not sure why it isn't working for you.  Does it work if you try to change the username, rather than set a password?
2) The admin password is set via an environment variable - ADMIN_PASSWORD.  I don't know of a built-in way to change the password in sails-auth, but it should be possible to create an endpoint to manually update the passport model that corresponds to the user id.  The password will get hashed automatically by a lifecycle hook.  See here for an instance of the passport model being queried: https://github.com/tjwebb/sails-auth/blob/master/api/services/protocols/local.js#L86

We will look at creating a built-in way to update the password for local strategy, thanks for creating an issue.

**Comment by ksylvan** [comment]
Authenticated as "admin" (user id 1), I I was not able to PUT to /user/2 to change username, but I was able to do the exact same PUT to /user/1 (changed the username to "adminadmin").

I've followed the sails-permissions setup, and trying to figure out what I might be doing wrong here. config/policies.js looks like this:

    module.exports.policies = {
      // sails-permissions setup
      //
      '*': [
        'basicAuth',
        'passport',
        'sessionAuth',
        'ModelPolicy',
        'AuditPolicy',
        'OwnerPolicy',
        'PermissionPolicy',
        'RolePolicy',
        'CriteriaPolicy'
      ],

Thanks for any suggestions.

**Comment by ksylvan** [comment]
Okay, I see about changing passwords. In the sails console, I can do things like:

    sails.models.passport.update({protocol: 'local', user: 2}, {password: 'admin12345'}).then(console.log)

And that works because of the lifecycle callback. However, how do I only give access to an authenticated user to be able to change only their password, and for the admin user (to be able to change anyone's password) within the sails-permissions framework?

**Comment by ryanwilliamquinn** [comment]
I would try `PUT` to a url like /user/:id/pwreset.  In that case you would need a permission for registered users to update 'User', with relation 'owner'.  The admin user should have permissions for that already.  I'm unsure why that isn't working for you.  I will try to test that later today.

**Comment by ksylvan** [comment]
Thank you.

I don't see any relation: 'owner' in the default permissions set when I do

    Role.find({name:'admin'}).populate('users').populate('permissions').then(console.log)

The only thing I see is relation: 'role'

**Comment by ryanwilliamquinn** [comment]
Yeah, the admin user should have 'role' permissions.  Role permissions mean you have permissions on any of the models.  Try this:
`Role.find({name:'registered'}).populate('users').populate('permissions').then(console.log)`

**Comment by ksylvan** [comment]
I see this (formatted for clarity):

    users:
      - admin (createdBy: 1, owner: 1, model: 5, id: 1)
      - kayvan (createdBY: 1, owner: 2, id: 2)
    permissions:
      - model: 3, action: read, role: 2, relation: role
      - model: 2, action: read, role: 2, relation: role
      - model: 5, action: update, role: 2, relation: owner
      - model: 5, action: read, role: 2, relation: owner
    name: resgistered

**Comment by ryanwilliamquinn** [comment]
Could you tell me the names of the models?  ie:
`Model.find(5, {select: ['identity']}).then(console.log)`

**Comment by ksylvan** [comment]
[ { identity: 'user' } ]

**Comment by ksylvan** [comment]
Model.find({}, {select: ['id', 'identity']}).then(console.log)

    [ { id: 1, identity: 'host' },
      { id: 2, identity: 'model' },
      { id: 3, identity: 'permission' },
      { id: 4, identity: 'role' },
      { id: 5, identity: 'user' } ]

**Comment by ryanwilliamquinn** [comment]
So, this should work.  The registered role has update permissions on `user` when they are the owner.  Admin user has update permissions on `user

**Comment by ryanwilliamquinn** [comment]
What versions of sails permissions and sails auth are installed?

**Comment by ksylvan** [comment]
$ npm list|grep sails
    ├── grunt-sails-linker@0.9.6
    ├─┬ sails@0.11.0
    │ ├── sails-build-dictionary@0.10.1
    │ ├─┬ sails-generate@0.12.3
    │ │ ├── sails-generate-adapter@0.10.5
    │ │ ├── sails-generate-api@0.10.0
    │ │ ├── sails-generate-backend@0.12.2
    │ │ ├─┬ sails-generate-controller@0.10.8
    │ │ ├── sails-generate-frontend@0.11.5
    │ │ ├── sails-generate-generator@0.10.11
    │ │ ├── sails-generate-gruntfile@0.10.10
    │ │ ├─┬ sails-generate-model@0.10.10
    │ │ ├─┬ sails-generate-new@0.10.21
    │ │ ├── sails-generate-sails.io.js@0.11.7
    │ │ ├── sails-generate-views@0.10.5
    │ │ └── sails-generate-views-jade@0.10.3
    │ ├─┬ sails-hook-sockets@0.11.24
    │ ├── sails-stringfile@0.3.2
    │ ├─┬ sails-util@0.10.6
    ├─┬ sails-auth@1.3.1
    │ └── sails-generate-entities@0.11.4
    ├─┬ sails-disk@0.10.8
    ├─┬ sails-permissions@1.4.2
    │ ├── sails-generate-entities@0.11.4

**Comment by ryanwilliamquinn** [comment]
So yeah, this should work fine.  If you create a new route that starts with /user (ie /user/:id/password), it should be governed by user permissions.  Does that make sense?

**Comment by ksylvan** [comment]
I don't know why I am getting a 404 when doing a PUT to /user/2 (as admin) to change username, but the exact same PUT to /user/1 succeeds.

**Comment by ryanwilliamquinn** [comment]
Is there a user with id 2?

**Comment by ryanwilliamquinn** [comment]
Can your admin user `GET /user/2`?

**Comment by ksylvan** [comment]
Yes. I get this response:

    {
      "createdBy": 1,
      "owner": 2,
      "username": "kayvan",
      "email": "kayvansylvan@gmail.com",
      "createdAt": "2015-08-28T04:56:43.723Z",
      "updatedAt": "2015-08-28T04:56:43.750Z",
      "id": 2,
      "gravatarUrl": "https://gravatar.com/avatar/7277dbbb5e7309fb4b2e302043b3b1eb"
    }

**Comment by ksylvan** [comment]
I removed the "How to update password?" part of the title, since that seems to be a separate issue and can be dealt with by a special user action/endpoint. The generic "Why can't admin PUT to /user/:id" question still remains.

**Comment by ksylvan** [comment]
@ryanwilliamquinn Did you get a chance to look at why the PUT with { username: "newusername" } does not work with /user/2 but works as expected with /user/1?

**Comment by ksylvan** [comment]
Tried again with a clean clone of your sails-permissions-example repo.

1) "sails console" to get the server up.

Users created with IDs: {admin = 1, travis = 2, venise = 3}

2) Using POSTMAN, GET /user/1 => "You are not permitted to perform this action."

3) POST credentials to /auth/local => authenticated successfuilly as "admin"

4) GET /user/1 => Get the user 1 record as json.

5) GET /user/2 => Get the travis (user 2) record

6) PUT /user/2 => Works as expected. username changed to "travis2"

So now I am left with the puzzle of what is different in my non-working example... Hmmmm...

**Comment by ksylvan** [comment]
The other puzzle is figuring out why the status code for the offending PUT is 404 (not found) rather than 403 (not permitted).

**Comment by ryanwilliamquinn** [comment]
You can do some debugging in the sails-permissions policies in your project to see what is going on.  Log the permissions and results of findTargetObjects in node_modules/sails-permissions/api/policies/permissionPolicy and rolePolicy.  If your project is on github, I can try to pull it down and debug it.

**Comment by ksylvan** [comment]
Okay, I finally was able to reproduce the problem. I think my problem may be with queries and how they interact was with the way I am using the sails-disk adapter.

In connections.js, I had added:

      localUserDb: {
        adapter: 'sails-disk',
      },

And then I had in api/models/User.js, I have:

    connection: 'localUserDb'

The localUser.db and localDiskDb.db are created in .tmp, and everything seems to work. In particular, you can do a GET of /user/2 after doing the POST to /user to create that user.

However, the PUT to /user/2 gets a 404 Not Found error.

**Comment by ksylvan** [comment]
Here's a sample application that demonstrates the issue:

https://github.com/ksylvan/sails-permissions-debug

**Comment by ryanwilliamquinn** [comment]
Thanks, I will take a look at it now.

**Comment by ryanwilliamquinn** [comment]
I think the problem may be related to having two different sails-disk adapters defined.  I was able to update users after doing the following steps:
1. delete all the local disk dbs in projectDirectory/.tmp/
2. delete the localUserDb connection from config/connections.js
3. delete the line in api/models/user that specifies it should use the localUserDb
4. in config/env/development.js,  set the `models` property like this:
```   models: {
     connection: 'localDiskDb'
   }```

**Comment by ryanwilliamquinn** [comment]
Do you need to have multiple sails-disk databases for any reason?

**Comment by ksylvan** [comment]
My thinking was that having multiple disk files would make it easier to save/restore databases later.

Yes, of course I can remove the localUserDb and it works just like your sails-permissions-example repo.

The problem I have is that changing the ORM/connections layer should not have an effect on the queries and routes like that.

What if you want to store all your Users in one database (say, some MySQLDB) and other data in other databases (MongoDB, etc.)? How you choose to store your data should not affect how the blueprint routes and REST API work.

**Comment by ksylvan** [comment]
This seems like a bug (not sure it's with sails-permissions or the waterline/ORM modules of sails in general). Especially when you consider that GET /user/2 works as expected, but PUT /user/2 fails with a 404 (not found) status.

**Comment by ryanwilliamquinn** [comment]
I agree.  If I revert back to sails-permissions v1.3.1 updating works fine.  I will try to track down where exactly it breaks.  Thanks for your help uncovering this issue.

**Comment by ksylvan** [comment]
You are welcome. I'd be happy to test your fix when you track it down.

**Comment by tjwebb** [comment]
> My thinking was that having multiple disk files would make it easier to save/restore databases later.

@ksylvan surely you're not using sails-disk in production. If you are, that's not a good idea.

**Comment by ksylvan** [comment]
@tjwebb No, I'm not. Thanks for asking.

This is all while I'm developing the app. In the end, I'll probably use something like redis. This is an internal app and has very light requirements on the database backend in terms of queries and storage.

I have another issue open with sails-permissions and redis (https://github.com/tjwebb/sails-permissions/issues/121).

**Comment by tjwebb** [comment]
@ksylvan understand. Since redis isn't a persistent datastore, we've not tested on it much. Do you have a permanent datastore in which you're storing your permissions?

**Comment by ksylvan** [comment]
@tjwebb Actually, redis is a perfectly fine persistent store for low-volume apps such as the one I'm creating. It drops an rdb file in /data at regular intervals.

I'll probably use mysql or progresql if I get to the point that I need a bigger/better backend database.

**Comment by tjwebb** [comment]
@ksylvan if you move to a more typical setup and still have issues, let us know. Your setup is extremely specific and fussy.

1. sails-disk should never, ever be used outside of a development scenario. For example, once you reach more than about 1,000 records, sails-disk will probably crash.
2. redis is not designed as a persistent datastore, and none of our projects test it as if it were. sails-permissions will likely never be tested in this situation. Just because it's possible doesn't mean it's a good idea.
3. the sails-redis adapter support for associations was just added a couple weeks ago, and is not heavily used. (see # 2). there are probably bugs.

**Comment by ksylvan** [comment]
Okay, no problem, and thank you for looking into it. I opened the issue on the PUT/GET weirdness, and I'm happy to help in whatever way to debug and make the code better. Like I said earlier, I don't think that a config change at the connections/ORM layer should affect routes and the REST functionality, so the issue still points to a bug.

As a practical matter (to keep moving forward on my app), I removed the multiple sails-disk adapters in the development setup and everything is working for me.

**Comment by tjwebb** [comment]
> Like I said earlier, I don't think that a config change at the connections/ORM layer should affect routes and the REST functionality, so the issue still points to a bug.

Exactly. If sails-permissions works with other adapters, then it points to a bug in the adapters you're using, or your configuration, or both.

**Comment by ksylvan** [comment]
The only configuration change (as reproduced above with the example app I started from scratch) was having multiple sails-disk adapters. As @ryanwilliamquinn noted above, if he reverts to using sails-permissions 1.3.1, the GET and PUT routes and permissions work as one would expect (even with the odd configuration).

So, while I agree that there are probably bugs in the sails-redis adapter or perhaps even in the sails-disk adapter, I still maintain that making a simple config change in how/where models are stored should not result in the REST API breaking like that.

In any case, I *love* the sails-permissions work you guys have done and am happy to use whatever the supported/recommended setup is. The obvious workaround for me for now is to have everything in the one default sails-disk DB while I am doing my development and set up my production environment with something like mysql as the datastore.

**Comment by tjwebb** [comment]
> if he reverts to using sails-permissions 1.3.1, the GET and PUT routes and permissions work as one would expect 

This is irrelevant. Because some previous version of sails-permissions does not expose the same bugs in other modules does not mean that that version of sails-permissions *fixes* any sort of problem.

> should not result in the REST API breaking like that.

We can go in circles about this all day. If you use a `this-might-break-things` configuration, stuff might break. The REST API is directly tied to the correct functioning of the adapters.

**Comment by ksylvan** [comment]
Okay, fine. I guess the conclusion of this discussion is:

1. Use the recommended/most common configuration setup, and...
2. If you find some non-standard config breaks something, propose a fix/pull-request.

Do I have that right? :-)
