### ISSUE TITLE
How to config facebook auth?

### ISSUE THREAD

**Issue by jaime-franco** [tjwebb/sails-permissions#138]
I added facebook provider into config/passport.js 

```javascript
facebook: {
    name: 'Facebook',
    protocol: 'oauth2',
    strategy: require('passport-facebook').Strategy,
    options: {
      clientID: 'your-client-id',
      clientSecret: 'your-client-secret'
    }
  }
```

But for some reason i get a not found everytime i test /auth/facebook i get redirected to /login, is there any other configuration that should be done? for make facebook auth work?

**Comment by igiigi** [comment]
+1

**Comment by igiigi** [comment]
Please see working example
// config/passport.js

var _ = require('lodash');
var _super = require('sails-permissions/config/passport');

_.merge(exports, _super);
_.merge(exports, {
  passport:{
    facebook: {
      name: 'Facebook',
      protocol: 'oauth2',
      strategy: require('passport-facebook').Strategy,
      options: {
        clientID: 'your-client-id',
        clientSecret: 'your-client-secret'
      }
    }
  }
  // Extend with custom logic here by adding additional fields, methods, etc.
});

**Comment by tjwebb** [comment]
This should be filed in sails-auth
