### ISSUE TITLE
The 'user' relation

### ISSUE THREAD

**Issue by sylvainlap** [tjwebb/sails-permissions#141]
For one Permission, the relation can be 'role', 'owner' or 'user'.
I understand the role & owner permissions, but what about the user relation ? There is no documentation on that type of relation.

Thanks !

**Comment by ryanwilliamquinn** [comment]
That is a relatively new feature, we should add some documentation on it.  The basic idea is, if you have a permission that is only going to be assigned to a single user, there is no point in creating a role.  It is an enhancement to reduce creating unnecessary role objects.

**Comment by sylvainlap** [comment]
Ok, thanks!
