### ISSUE TITLE
res.ok returns 404 when no records found

### ISSUE THREAD

**Issue by dottodot** [tjwebb/sails-permissions#151]
When using ```find()``` and ```res.ok``` I'm getting a 404 when no records are found which isn't the ideal response when retrieving multiple models. So as a work around I'm having to do the following

```
if(products.length === 0) return res.send(products);
res.ok(products);
```

**Comment by ryanwilliamquinn** [comment]
Which version of sails permissions are you using?

**Comment by ryanwilliamquinn** [comment]
I think this issue is solved by this PR: https://github.com/tjwebb/sails-permissions/pull/105/files

@tjwebb we should merge that in

**Comment by ryanwilliamquinn** [comment]
I think this PR will solve the issue: https://github.com/tjwebb/sails-permissions/pull/105

@tjwebb lets merge that in

**Comment by dottodot** [comment]
Yes just tried that PR and it works now.
