### ISSUE TITLE
Cannot find module sails-permissions\generator

### ISSUE THREAD

**Issue by ronenteva** [tjwebb/sails-permissions#156]
I've never used the .sailsrc file before, so it could be something that I did wrong, but I think the documentation should be updated to make it more idiot-proof.

running `sails generate permissions-api` resulted in:

    Error: Cannot find module 'C:\Source\app\sails-permissions\generator'

Adding `node_modules` to the .sailsrc line fixed the issue:

    {
      "generators": {
        "modules": {
          "permissions-api": "node_modules/sails-permissions/generator"
        }
      }
    }

**Comment by achernyak** [comment]
You should omit the `node_modules` part in your path. It should just be `sails-permissions/generator`

**Comment by stewhouston** [comment]
Can confirm OP's results. Without "node_modules/" in the .sailsrc an error is thrown, unless we're both doing something wrong.

**Comment by tjwebb** [comment]
> It should just be sails-permissions/generator

@stewhouston @ronenteva are you guys both using Windows?

**Comment by stewhouston** [comment]
@tjwebb It is the bane of my existence (... yes.)

**Comment by tjwebb** [comment]
Yea I've seen this issue before in other (unrelated) projects. I think it's a bug in node.js, since the behavior on linux and windows is different.

**Comment by ronenteva** [comment]
Yes, I'm using windows too.
Is it an issue with the .sailsrc file or unrelated?
I can't find any reference to such issue by using Node on windows, perhaps you can refer us to a starting point?

**Comment by boadude** [comment]
If u use windows u must put the node_module path and work

**Comment by abedbilani** [comment]
it should be like that
{
  "generators": {
    "modules": {
      "permissions-api": "node_modules/sails-permissions/generator"
    }
  }
}
