### ISSUE TITLE
Typo in Permission Service breaks removeUsersFromRole()

### ISSUE THREAD

**Issue by grego3** [tjwebb/sails-permissions#159]
There is a typo on line 353 of `api/services/PermissionService` that breaks the `removeUsersFromRole()` function in the Permission Service. This bug essentially renders this function useless and doesn't allow for a convenient way to revoke roles from users.

Line 353 currently reads:
`role.users.remove(user.id);`

It **should** read:
`role.users.remove(users.id);`
*Note the change from `user.id` to `users.id` in the argument passed to `remove()`*

Tested locally and this seemed to fix the issue.

**Comment by grego3** [comment]
Sorry, just realized this appears to be fixed in 2.0.0-alpha.

**Comment by ryanwilliamquinn** [comment]
Thanks for bringing this up.  This is fixed in master and in 2.0.
