### ISSUE TITLE
Cannot lift after having installed

### ISSUE THREAD

**Issue by tomhallam** [tjwebb/sails-permissions#16]
Hi there,

Followed the installation instructions, on a cleanly generated sails app, but after applying the policies to my policies.js configuration file as described, the app won't start.

    error: Unknown policy, "basicauth", referenced in `config.policies`.

After a bit of digging, it looks like these files aren't being copied from your "api" folder. I copied them over from this repository. Now I'm greeted with a new error:

    Error: Collection user has an attribute named passports that is pointing to 
    a collection named passport which doesn't exist. You must  first create the passport collection.

Can you explain this? I think this library could be really useful - really want to get it going!

~T

**Comment by tjwebb** [comment]
Let me try to re-create. I haven't seen this, and everything passes in Travis-CI.

Is the source code of project you're using this for public?

**Comment by tjwebb** [comment]
Ah yea, it looks like I forgot to list a couple of the files to be generated. For my integration tests I'm lifting from inside the sails-permissions directory, and so all the files are obviously and necessarily present.

I'll fix this

**Comment by tomhallam** [comment]
Can confirm this is now working. Slightly off topic, but now I have it installed - how do I use it?! 

Documentation in /docs folder only really just tells me the layout of the ORM models, but I'm pretty unclear how to disable access to certain controller methods, etc.

Can you provide some basic documentation?

Thanks,
~T

**Comment by dbkaplun** [comment]
This is happening again:
```
Error: Collection permission has an attribute named criteria that is pointing to a collection named criteria which doesn't exist. You must  first create the criteria collection.
  at JoinTables.parseAttribute (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/joinTables.js:143:11)
  at /usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/joinTables.js:83:22
  at Array.forEach (native)
  at JoinTables.buildJoins (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/joinTables.js:82:24)
  at new JoinTables (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/joinTables.js:40:23)
  at new module.exports (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema.js:33:17)
  at [object Object].Waterline.initialize (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:107:17)
  at buildORM (/usr/local/lib/node_modules/sails/lib/hooks/orm/build-orm.js:52:15)
  at Array.async.auto.instantiatedCollections (/usr/local/lib/node_modules/sails/lib/hooks/orm/index.js:203:11)
  at listener (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:493:46)
  at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:444:17
  at Array.forEach (native)
  at _each (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:46:24)
  at Immediate.taskComplete (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:443:13)
  at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by dbkaplun** [comment]
Works if you install `sails-auth` first, then `sails-permissions` (you will have to remove some of the files generated by `sails-auth`).

**Comment by tjwebb** [comment]
That's a different error; we added some new models and functionality in 1.1. What's needed is actually documentation for the upgrade path, and to rely less on the "generator" feature.

**Comment by ayyappaappana** [comment]
Still error: 
-------------
debug: marlinspike (permissions): loading Models...
debug: marlinspike (permissions): loading Controllers...
debug: marlinspike (permissions): loading Policies...
error: Unknown policy, "basicauth", referenced in `config.policies`.
error: Are you sure that policy exists?

Node Version: v0.12.7
NPM Version: 2.11.3
Sails Version:0.11.0

Please guide me how to resolve this issue. I re-installed sails even, I followed the steps from 
http://threeninetyfive.net/blog/2015/07/14/sails-permissions-by-example/  (from creating of my new application).

**Comment by ryanwilliamquinn** [comment]
what versions of sails permissions and sails auth are installed?  That example is based on sails-permissions and sails-auth 1.x

**Comment by ayyappaappana** [comment]
@ryanwilliamquinn
  "sails-permissions": "^2.0.3"
  "sails-auth": "^1.3.1" 

Copied from packages.json

**Comment by ryanwilliamquinn** [comment]
Run `npm install --save sails-permissions@1.x` in your project if you want to follow along with that tutorial.  I will try to update it for sails 2.x soon.

**Comment by ayyappaappana** [comment]
I used the below command but still it shows,

npm install --save sails-auth@1.x sails-permissions@1.4.2 

after some random system trails i found that

"sails-permissions": "^1.4.2" this version is working perfect for my concern, but it was a random linux environment, cant track how this version is installed in that PC, can you guide how to install the exact version of sails-permissions, the same is not working in my ubuntu environment.

**Comment by ryanwilliamquinn** [comment]
did you redo the tutorial from the beginning using sails-permissions@1.4.2?

**Comment by ayyappaappana** [comment]
Thanks so much, it is working fine for now, but its better to update for 2.x also and big smile for quick response.

**Comment by dottodot** [comment]
I'm having the same problem using sails-auth 1.3.1 and sails-permissions 1.4.2, and sails 11.2

What's odd is I've got it to work on a different laptop and the only difference I can think of is that is running node v0.10.36 whereas the one that doesn't work has node v0.10.37
