### ISSUE TITLE
If I create a new model after having installed, I receive database errors

### ISSUE THREAD

**Issue by tomhallam** [tjwebb/sails-permissions#19]
Hi there,

Have noticed since installing and generating the permissions hooks, I get database errors if I create a new model. It seems the script doesn't check whether there is an existing model representation before attempting to create a new one.

I assume using this method it would also invalidate any current permissions every time the app is re-initialised.

This could potentially be solved by using a findOrCreate method instead of just a create in your model fixtures.

~T

**Comment by tjwebb** [comment]
Thanks for the report, I'll look into it.

**Comment by tjwebb** [comment]
What adapter are you using? It does attempt to create duplicate, but should just ignore the error. 

btw, I think `findOrCreate` is going to be deprecated

**Comment by tomhallam** [comment]
Using the stock mongodb adapter.

Findorcreate is far from perfect but I think it's valuable, can you link me
to deprecation thread?

~T

**Comment by tjwebb** [comment]
https://github.com/balderdashy/waterline/pull/843

Check the latest release. I check for existence before creating the models.

**Comment by heygrady** [comment]
Fresh install of Sails and sails-permissions. Getting errors after restarting sails because the fixtures have already created all of my records. Using `sails-mysql`.

I was able to fix it by wrapping the `create` calls in a `findOne`.

In `sails-permissions/config/fixtures/model.js`
```js
exports.createModels = function () {
  sails.log('Installing Models');

  var models = _.compact(_.map(sails.controllers, function (controller, name) {
    var model = sails.models[name];
    return model && model.globalId && model.identity && {
      name: model.globalId,
      identity: model.identity,
      attributes: _.omit(model.attributes, _.functions(model.attributes))
    };
  }));

  return Promise.map(models, function (model) {
    sails.log('creating', model.name);
    // return Model.create(model);
    // wrap the `create` in a `findOne` to check for existence
    return Model.findOne({ name: model.name }).then(function(existing) { return existing || Model.create(model); });
  });
};
```
In `sails-permissions/config/fixtures/role.js`
```js
exports.create = function () {
  return Promise.all([
    Role.findOne({ name: 'admin' }).then(function(existing) { return existing || Role.create({ name: 'admin' }); }),
    Role.findOne({ name: 'registered' }).then(function(existing) { return existing || Role.create({ name: 'registered' }); }),
    Role.findOne({ name: 'public' }).then(function(existing) { return existing || Role.create({ name: 'public' }); })
  ]);
};
```

**Comment by tjwebb** [comment]
The unit tests use sails-disk so I missed this one for awhile
