### ISSUE TITLE
Best Way to Prevent Unwanted Updates on Current User

### ISSUE THREAD

**Issue by GeekLad** [tjwebb/sails-permissions#190]
I'm working on building CRUD interfaces to manage ```User```, ```Role```, and ```Permission``` and I want to put in some server-side safeguards to prevent a logged-in admin user from performing some unwanted updates on its own account:

* Delete itself
* Remove the admin role from itself
* Removing CRUD operations from itself for Permissions to prevent the admin from removing a permission it won't ever be able to get back

Prevention of a delete operation on the current user wasn't too difficult.  I created a policy called ```isNotSelf``` and put it on the ```delete``` action for the ```UserController```.  It compares the ```id``` of the current user to the ```id``` of the user for the ```delete``` operation, and if they're the same it results in a ```res.badRequest()```.

To easily modify role assignments I:

* added a ```roles``` collection to the ```User``` model
* use the REST API by passing an array of ```[role.id]``` to ```PUT /user/id```
* if a role id is missing from the array that the user had previously, the role is removed
* if a role id is in the array that the user did not have previously, the role is added

To prevent an admin user from removing the admin role from itself, it seems a ```beforeUpdate``` lifecycle callback in the ```User``` model seems would be in order.  However, I'm not sure how to get the ```id``` of the current logged-in admin user from there.  I think I probably also need to put a similar safeguard on the ```RoleController``` to prevent the removal of the currently logged in user via modifications to the ```Role``` model.

The same goes for disallowing CRUD operations on Permissions.  It seems like the best place to insert this safeguard would be in a ```beforeUpdate``` lifecycle callback, but I don't know how to get the currently logged-in user id.

Please help!

**Comment by CovertIII** [comment]
The logged in user id can be accessed from a controller in the request object, req.user.id.  You can override the default controller actions defined by the blueprint.  See http://sailsjs.org/documentation/reference/blueprint-api#/blueprint-actions.  You can then create a custom method on the model, call it on the controller action and pass the user id into that.

**Comment by GeekLad** [comment]
@CovertIII good tips.  I was hoping to try to keep as much in-tact by not having to override blueprints with customizing the default actions, but that may be the only way.  Is there an easy way to call the default blueprint action within a custom controller action?  That would at least make it a bit easier/convenient, because then you can perform a simple check to make sure the current user isn't going to do something silly, and then either pass the request on through to the default blueprint or stop it dead in its tracks.

**Comment by CovertIII** [comment]
Your RoleController could look like this:
```javascript
   // api/controllers/RoleController.js

var _ = require('lodash');
var _super = require('sails-permissions/api/controllers/RoleController');

_.merge(exports, _super);
_.merge(exports, {

    destroy: function(req, res){
      if(req.params.id !== req.user.id){
          Role.destory({id: req.params.id}).then(function(result){
             res.json(result);
          }).catch(function(error){
             res.json(error);
          });
      }else{
          res.badRequest()
      }
    }
});
```

Not sure if it's the best way, but it should do the trick.

**Comment by ryanwilliamquinn** [comment]
I haven't tried these, but here are some thoughts -

Delete itself:
Remove the delete user permission from admin role, and add a delete user permission that allows for delete where id != whatever the id is for the admin user (although it sounds like you already have a solution)

Remove the admin role from itself:
Same idea as above - remove global delete permission role from admin, and add one that excludes deleting the admin role

Removing CRUD operations from itself for Permissions to prevent the admin from removing a permission it won't ever be able to get back:
Why do you have to remove CRUD operations for Permissions for the admin role?  Seems like you just want to remove delete operations for the admin role?  Maybe I am misunderstanding.  Anyway, in the same vein, you could remove the delete permission and create a new one that disallows deleting permissions that have role: adminrole.

Does this path make sense?  Keep in mind this only works for requests, you can still do whatever you want in your controller/service logic to wreak havoc on your permissions.
