### ISSUE TITLE
Is it possible to add a limit create permission?

### ISSUE THREAD

**Issue by EloB** [tjwebb/sails-permissions#193]
I would like to add a limitation on the amount of "create" to a permission on a role. The user-case is like bronze, silver and gold subscriptions. These roles should be able to create a specific model but in a limited amount. Is that possible?

**Comment by khchan** [comment]
What immediately comes to mind is using a Permissions' Criteria to achieve this:
```
{
  model: 'Item',
  action: 'create',
  criteria: [ { where: { count: { '<': 5 } } ]
}
```

**Comment by EloB** [comment]
Nice! :+1:
