### ISSUE TITLE
Mess of installing

### ISSUE THREAD

**Issue by DaAwesomeP** [tjwebb/sails-permissions#203]
OK,
So I'm trying to set up Sails with `sails-postgres`, `sails-permissions`, and `sails-auth`. I'm really confused about the version mismatches everyone, some in issues dating back to October.

1. What versions of `sails-auth` and `sails-permissions` should I install?
2. I do not plan on moving from Sails v0.11.x release to the `master` branch of it, as it is the stable release and I will need this app to be reliable and not too frequently updated in production.

cc @tjwebb

**Comment by tjwebb** [comment]
sails-permissions 2.x series will only work with Sails 0.12.x series. 

re reliability: https://github.com/tjwebb/sails-permissions/issues/200

**Comment by DaAwesomeP** [comment]
Wow! I had no clue about TrailsJS. Since I'm just starting my app, I think that I'll switch to it. It even uses ES6!

You might consider adding a large warning to the readme.

**Comment by tjwebb** [comment]
Yes, we'll update all the readme on all our Sails modules once trails 1.0-alpha is releases in the first week of January.

Sorry for the inconvenience.
