### ISSUE TITLE
Custom actions

### ISSUE THREAD

**Issue by blah238** [tjwebb/sails-permissions#21]
One thing that may be blocking for some people is that the actions that may be protected by this is limited to CRUD actions. How difficult would it be to allow custom actions to be defined, so that for example, a `User` could be given permission to execute a `run` action on a given `Task`?

**Comment by tjwebb** [comment]
This is something I've included the scaffolding for but I haven't been able to build out yet. I'd like support custom actions (controller endpoints) and also support attribute-level security. Both of these fields are already available in the Permission object:

- attribute: https://github.com/tjwebb/sails-permissions/blob/master/api/models/Permission.js#L36-L45
- service (controller method, or other endpoint): https://github.com/tjwebb/sails-permissions/blob/master/api/models/Permission.js#L59-L67

So you can set these fields to control access to attributes and services, but I haven't yet written the logic that enforces them.

**Comment by kievechua** [comment]
Hi, may I know what's the current status for this issue?

**Comment by tjwebb** [comment]
It's scheduled, but I haven't had time to get to this yet. I'd be happy to collaborate on this with anyone who'd like to help out.

**Comment by bgulotta** [comment]
I would be happy to help out. If we can start by iterating all the unit tests we can think of w/inputs and expectations, I can start writing all the unit tests. They will be broken for now, but will start popping green as the code is worked.

**Comment by bgulotta** [comment]
I just got back from a family vacation so I have time to start working on this now. I am starting to add in unit tests to test all the functionality currently in the PermissionService and then start adding in all the new ones to test the security of model attributes and custom controller actions. Once I get all those added in my fork and ready to go I will let you know.

**Comment by jerrywuz** [comment]
+1

**Comment by zxshinxz** [comment]
+1
