### ISSUE TITLE
Password unencrypted in User collection on initial set up

### ISSUE THREAD

**Issue by bmsterling** [tjwebb/sails-permissions#24]
In the process of grasping how to use sails-permissions, I noticed that the password being added to the `User` collection was not being encrypted via `bcrypt` but it is being encrypted when it's added to the `passport` collection.  I was going to address this but I am not clear of the entire flow of the app on initial start up, ie. `sails lift`.

Can you point me to where I should looks to make the password encrypted for insertion into `user` collection?

**Comment by tjwebb** [comment]
> I noticed that the password being added to the User collection was not being encrypted via bcrypt but it is being encrypted when it's added to the passport collection.

There should be no password stored at all on the `User` object. All passwords should be hashed and stored on the `Passport` object. Can you share your example where this is happneing?

**Comment by bmsterling** [comment]
I'm still stepping thru the code, but I have clean install of `sails` and `sails-permissions` with all the set up you have in the readme and at this point no code outside of what was added via the set up of the app.

It's happening before line `69` inside the `sails-permission.js` file.  Just before `return user.save();` I've added `user.password = '';` and that makes a blank password field in the `user` collection.  If I do `delete user.password`, the filed still gets that password value, so it's being saved before the `.then` at line `64`.  What I can't figure out yet, is where the initial save is happening to the user collection.

Let me know if that is not clear.

**Comment by tjwebb** [comment]
>  What I can't figure out yet, is where the initial save is happening to the user collection.

That's done via passport.js. 

>  If I do delete user.password, the filed still gets that password value, so it's being saved before the .then at line 64

Ok I'll look into this and figure out how it's ending up getting saved.

> delete user.password, the filed still gets that password value, so it's being saved before the .then at line 64. What I can't figure out yet, is where the initial save is happening to the user collection.

**Comment by bmsterling** [comment]
Thanks, @tjwebb, I'll dig into what passport.js local to see what it is doing as well.

**Comment by bmsterling** [comment]
@tjwebb looks like the origination of the issue is in the `sails-auth` library, `sails-auth/api/services/protocals/local.js`.  This line specifically: `return sails.models.user.create(_user, function (err, user) {`.

I'll create an issue in the `sails-auth` repo.

**Comment by tjwebb** [comment]
can you confirm that your PR in sails-auth resolved this in sails-permissions?

**Comment by bmsterling** [comment]
Yes.  I've confirmed that the user record gets created minus the password and the passport record still has the encrypted password.  This is in the clean install of sails and sails-permission.

**Comment by tjwebb** [comment]
Great, thanks. I'll publish a new version of sails-auth to npm
