### ISSUE TITLE
implement attribute-level security

### ISSUE THREAD

**Issue by tjwebb** [tjwebb/sails-permissions#25]
### AttributePolicy
  - implement logic to check if operation might violate `attribute` field is set on `Permission` object
  - return error for `update` action
  - delete Permission invalid; subset of `update`. attributes cannot be deleted.
  - create Permission invalid; attributes cannot be created.

### AttributePolicyResponse
  - automatically strip out non-permitted attributes in `read` operations

**Comment by jerrywuz** [comment]
yeah , I want this feature.
For example, User A can update Model(topic) 's status ,User B only can update Model(topic) 's name.

**Comment by zxshinxz** [comment]
+1 
this would be awesome

**Comment by tjwebb** [comment]
@zxshinxz this feature actually exists in master via Criteria.blacklist: https://github.com/tjwebb/sails-permissions/blob/master/api/models/Criteria.js#L18. Thanks @ryanwilliamquinn

**Comment by tjwebb** [comment]
closed via https://github.com/tjwebb/sails-permissions/pull/69
