### ISSUE TITLE
Duplicate models, roles and permissions

### ISSUE THREAD

**Issue by dottodot** [tjwebb/sails-permissions#27]
Every time I lift my app it's adding the default models, roles and permissions each time, so this collections are ending up with lots of duplicates.

```
debug: Installing Models
debug: creating Model
debug: creating Permission
debug: creating Role
debug: creating User
```

This is using  Sails v0.10.5 with mongodb.

**Comment by bgulotta** [comment]
If you are in a development environment you could just change your sails models.config to 'drop'.

**Comment by dottodot** [comment]
Not really sure how that helps, surely it should only add these the first time you lift the app not every time.

**Comment by tjwebb** [comment]
I think I'm using `findOrCreate` there. If not, that's a bug. I'll check it out.

**Comment by dottodot** [comment]
This seems to have mostly fix creating duplicates however every time I restart it's adding 3 extra permissions.

They all have the role of "registered" and 1 for each model of "Permission", "Model", and "User"

**Comment by tjwebb** [comment]
Sorry about that; fixed.

**Comment by dottodot** [comment]
This has started happening again since I've updated to the latest version.
