### ISSUE TITLE
How to use the default admin username and password?

### ISSUE THREAD

**Issue by cratervale** [tjwebb/sails-permissions#29]
I am trying to get started with sails-permissions but I am unclear on how the default username and password work.

When trying to run the example in the docs using the authorization header 'Basic YWRtaW46YWRtaW4xMjM0'  (admin:admin1234)

POST /user
{
  username: 'tjwebb',
  email: 'me@traviswebb.com',
  password: 'test123'
}

"error": "Could not authenticate user admin"

I've also tried using 'admin@example.com' as the username.  What am I missing?

Btw I am using the sails-postgresql adapter.

**Comment by tjwebb** [comment]
> Basic YWRtaW46YWRtaW4xMjM0' (admin:admin1234)

The unit tests authenticate using admin@example.com / admin1234 and work fine. The auth header is here: https://github.com/tjwebb/sails-permissions/blob/master/test.js#L10.

Try this and let me know if you have issues.

**Comment by cratervale** [comment]
It seems as though the default admin user was not being created in my database.  I grabbed the changes that resolved issue #28,  ran `sails generate permissions-api --force`, and now the authentication is working as expected.  

Thanks!

**Comment by tjwebb** [comment]
Ok awesome. I'm not sure why that wasn't getting created, but I'm glad everything is working now. Let me know if you run into any other issues; thanks.
