### ISSUE TITLE
document basic use cases in README

### ISSUE THREAD

**Issue by tjwebb** [tjwebb/sails-permissions#3]

**Comment by tomhallam** [comment]
+1 on this - even basic documentation would be really handy

**Comment by tjwebb** [comment]
I recently did an overhaul of sails-permissions. I'll be adding docs shortly, sorry for the wait

**Comment by tjwebb** [comment]
I updated the README and added quite a bit of info in the wiki: https://github.com/tjwebb/sails-permissions/wiki

Hope that helps; let me know if you have any other questions

**Comment by tomhallam** [comment]
Thanks a lot for your input here, really impressed that you got some documentation out so quickly.

I'm still a little bit unsure as to how to apply this to my controller methods - are they automatically applied depending on the permission created? 

Also - I've noticed a bug, will open a seperate ticket. Seems like when you add a new model, it tries to recreate the older model's ... models! So I'm getting duplicate key entries in my MongoDB database. See #19

Perhaps using findOrCreate in your loop would solve the problem?

Thanks a lot for your help so far

**Comment by tjwebb** [comment]
Yes the permissions are automatically enforced for all REST requests by the policies that are included.
