### ISSUE TITLE
error: column permission.createdBy does not exist

### ISSUE THREAD

**Issue by cratervale** [tjwebb/sails-permissions#30]
When running `sails lift` or `sails console` I receive the following error.  Probably just a missing attribute?

```
verbose: Starting ORM...
verbose: orm hook loaded successfully.
debug: sails-permissions: syncing waterline models
debug: sails-permissions: admin user does not exist; creating...
debug: User.afterCreate.setOwner { username: 'admin',
  email: 'admin@example.com',
  createdBy: 1,
  owner: 1,
  id: 1,
  createdAt: Mon Mar 23 2015 14:39:47 GMT-0500 (CDT),
  updatedAt: Mon Mar 23 2015 14:39:47 GMT-0500 (CDT) }
debug: sails-permissions: created admin user: { createdBy: 1,
  owner: 1,
  username: 'admin',
  email: 'admin@example.com',
  id: 1,
  createdAt: Mon Mar 23 2015 14:39:47 GMT-0500 (CDT),
  updatedAt: Mon Mar 23 2015 14:39:47 GMT-0500 (CDT) }
error: Error (E_UNKNOWN) :: Encountered an unexpected error
error: column permission.createdBy does not exist
  at [object Object].Connection.parseE 

...

Details:  error: column permission.createdBy does not exist

```

**Comment by tjwebb** [comment]
Ah sorry man, I accidentally pushed some debug code into the release where I set autoCreatedBy to false on Permission. Things are sort of crazy in Balderdash-land right now and I wasn't paying attention; I'll fix this and be more careful in the future.

**Comment by cratervale** [comment]
No worries, I really appreciate all you're doing with this library, it takes a huge headache out of user management.  I'll keep adding tickets as I find issues.  Cheers to Balderdash, also!

**Comment by bgulotta** [comment]
Agree 100% cratervale!!!!

**Comment by pappu687** [comment]
Any update on this ?

**Comment by tongtwist** [comment]
Up! Got the same error.

**Comment by ryanwilliamquinn** [comment]
I haven't seen this error for a while now.
