### ISSUE TITLE
Error: Error.Passport.Password.Invalid on POST to /user

### ISSUE THREAD

**Issue by cratervale** [tjwebb/sails-permissions#31]
Following the example in the docs, I am trying to make a POST call to the /user endpoint to create a new user.  
```
{
  "username": "tjwebb",
  "email": "me@traviswebb.com",
  "password": "test123"
}
```
The action behaves as expected for adding a new row in the User table and linking the new user to the default 'registered' role (via role_users__user_roles table when using sails-postgresql adapter).  However, it errors before a new row is added to the Passport table.  Here's the log:

```
sails> debug: User.afterCreate.setOwner { username: 'tjwebb',
  email: 'me@traviswebb.com',
  createdBy: 1,
  owner: null,
  id: 3,
  createdAt: Mon Mar 23 2015 16:38:04 GMT-0500 (CDT),
  updatedAt: Mon Mar 23 2015 16:38:04 GMT-0500 (CDT) }
error: Sending 500 ("Server Error") response: 
 Error: Error.Passport.Password.Invalid

  at /[PROJECT]/node_modules/sails-auth/api/services/protocols/local.js:58:17
  at /[USER]/.node/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/create.js:73:22

...

 at /[PROJECT]/node_modules/sails-auth/api/services/protocols/local.js:51:14
  at /[USER]/.node/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/create.js:241:9
  at /[USER]/.node/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:157:25
  at /[PROJECT]/node_modules/sails-permissions/api/models/User.js:40:11
```

**Comment by cratervale** [comment]
I've tested this with `sails-disk` with the same results.

**Comment by bgulotta** [comment]
I haven't tested this myself yet, but I believe it could be caused because the min length of the password field being set at 8 characters.

**Comment by cratervale** [comment]
Ah yes, good catch!  This one was driving me nuts.  

There is a nasty bug that crashes the server if you attempt to make the same request with a different password.  I'm closing this ticket and making a new one for that behavior.
