### ISSUE TITLE
is there a decent sample app available showing the most important use cases?

### ISSUE THREAD

**Issue by paulvanbladel** [tjwebb/sails-permissions#38]
Is it possible to apply standard filter on model based on permission.
e.g  we have customer and order model with one to many relation.
i have permission based filter on customer (e.g. i can see only customers that i own and where customer type is abc). What happens when I query on orders with an "include" on customers.. Will the customer filter be applied automaticaly in the order context as well?
thanks

**Comment by Esya** [comment]
:+1:

**Comment by secrettriangle** [comment]
:+1:

**Comment by maheshchari** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by JHereu** [comment]
:+1: 

I've read in some other issue you can perform a lift directly from the sails-permissions module folder to launch a test app. Well, it launches and creates/stores some data in the database, but still unclear for me at least. Don't know what to do with that "example"...

**Comment by fuzzball1980** [comment]
https://camo.githubusercontent.com/a2840914d539225aaf8d395397d8dbc488a0740d/68747470733a2f2f6173736574732d63646e2e6769746875622e636f6d2f696d616765732f69636f6e732f656d6f6a692f756e69636f64652f31663434642e706e67

**Comment by fuzzball1980** [comment]
:+1: 
:+1: 
:+1:

**Comment by ryanwilliamquinn** [comment]
I've set up a simple app here: https://github.com/ryanwilliamquinn/sails-permissions-example

It has some users, roles, and permissions bootstrapped, so you can see how they are created.
