### ISSUE TITLE
Add support for custom model configuration inside controllers

### ISSUE THREAD

**Issue by chrisfrancis27** [tjwebb/sails-permissions#49]
Sails controllers may specify models that don't directly map to the controller names. For example, inside `api/controllers/MeatController.js` you could specify:

    module.exports = {
      _config: {
        model: 'fish'
      }
    };

Or, a more realistic example is namespacing the API with 'v1' etc, so inside `api/controllers/v1/MeatController.js`, in order to prevent sails looking for a model called `v1/Meat` you would specify:

    module.exports = {
      _config: {
        model: 'meat'
      }
    };

Currently sails-permissions loops over the controller names to derive the model names during creation. It would be good to check for custom configurations like the above and use that first, falling back to controller name if not found.

**Comment by tjwebb** [comment]
Ah, good catch. I'll take a look. Thanks for the PR!
