### ISSUE TITLE
npm registry 404

### ISSUE THREAD

**Issue by maheshchari** [tjwebb/sails-permissions#54]
while i am trying to install , it giving https://registry.npmjs.org/sails-permissions/-/sails-permissions-1.0.17.tgz 404. 
Can you fix ASAP. 
npm ERR! fetch failed https://registry.npmjs.org/sails-permissions/-/sails-permissions-1.0.17.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/sails-permissions/-/sails-permissions-1.0.17.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/sails-permissions/-/sails-permissions-1.0.17.tgz

**Comment by floriandejonckheere** [comment]
:+1:

**Comment by aaronfranco** [comment]
same problem

**Comment by tjwebb** [comment]
Republished, thanks.

see https://github.com/npm/npm/issues/8099
and https://github.com/npm/npm/issues/8100

**Comment by maheshchari** [comment]
Thank you for amazing contribution :+1:
