### ISSUE TITLE
Discrepancy between README.md and config/policies.js

### ISSUE THREAD

**Issue by dbkaplun** [tjwebb/sails-permissions#59]
* [config/policies.js](https://github.com/tjwebb/sails-permissions/blob/ab96af910822fcd4c38af6c76f283e94ec46edad/config/policies.js#L33) says `AuthController: {'*': true}`
* [README.md](https://github.com/tjwebb/sails-permissions/blame/52f19ab56392834810b87b37555b5f7251152a08/README.md#L61) says `AuthController: {'*': [ 'passport' ]}`

Which one do I use?

**Comment by tjwebb** [comment]
Strangely enough, in this case, I think the documentation is correct and the code is wrong.

**Comment by dbkaplun** [comment]
Indeed, I've been using `AuthController: {'*': [ 'passport' ]}` as in the README but frankly I don't remember why.

**Comment by tjwebb** [comment]
Alright I've synced everything up. Thanks for pointing that out.
