### ISSUE TITLE
User based permission

### ISSUE THREAD

**Issue by anthonybriand** [tjwebb/sails-permissions#63]
Hello,

Currently you have a role based permission but it can be useful to have (in addition to role based permission) a User based permission.

I will try to explain, I have : 
Model A
User A
User B

User A has created a record of Model A, however, User A does not want the User B (and only him) have access to that record.

Can I do this actually with sails-permissions ?

Thanks in advance for your response.

**Comment by tjwebb** [comment]
You're right, the only way to connect a User to a Permission is via a Role. This design is flexible enough, though, to do just about anything you'd want. Convenience methods can be added to make certain tasks easier.

If you have a Record R, you could theoretically create a new Role, which everyone except User B gets assigned, which grants permissions to see R. The awkardness here is that Roles are only additive and never subtractive, so you have to create a new Role to remove a privilege.

I've considered this, and I'd rather have a messy database with a bunch of Roles than introduce new complexity to the paradigm itself and possibly jeopardize conceptual integrity. But it'd certainly be excellent to improve the API to make this feature easier to attain.

Hope that helps.

**Comment by anthonybriand** [comment]
Ok, I will use another method because I will have about 100K users and many records with this use case, I will try to fork sails-permissions and add this behavior.

Thanks for your help.

**Comment by tjwebb** [comment]
So your main goal is instead of `User -> Role -> Permission` you'd like to be able to directly set `User -> Permission`. I think that's reasonable. Let me know if you need help / have questions. A PR would be great!

**Comment by anthonybriand** [comment]
Yes that's it, of course when I will done this part I will make you a PR

**Comment by anthonybriand** [comment]
Hi, just a little question : why did you choose to only have additive permissions ?
I have made a branch (from the user level permission) with the implementation here : https://github.com/anthonybriand/sails-permissions/tree/subtractive-permissions
