### ISSUE TITLE
There are practical examples of how to use it?

### ISSUE THREAD

**Issue by wfpaisa** [tjwebb/sails-permissions#70]
Hello, for us it is difficult to understand the operation. There are practical examples of how to use it?

It would be helpful to many people who are starting in sails.js and permissions need to integrate effectively.

**Comment by tjwebb** [comment]
@wfpaisa We're working on a blog post that will explain everything in more detail.

**Comment by Benew** [comment]
Would just love to know where to set the environment variables mentioned in the README

**Comment by ryanwilliamquinn** [comment]
Here is a rough draft of a sails permissions walkthrough - let me know if this helps:
http://threeninetyfive.net/blog/2015/07/14/sails-permissions-by-example/

**Comment by ryanwilliamquinn** [comment]
fuzzball1980 found this: http://theambitious.com/index.php/2015/07/26/sailsjs-sails-permissions-on-linux-quick-start/
