### ISSUE TITLE
peerDependencies error when installing 

### ISSUE THREAD

**Issue by ryanwilliamquinn** [tjwebb/sails-permissions#72]
This error is from a project using sails 0.12.0-rc2:

>npm WARN peerDependencies The peer dependency sails@>0.10.0 included from sails-permissions will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/Users/rquinn/.nvm/versions/node/v0.12.5/bin/npm" "install" "sails-permissions" "--save"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.3

>npm ERR! code EPEERINVALID
npm ERR! peerinvalid The package sails does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer sails-permissions@1.0.20 wants sails@>0.10.0
npm ERR! peerinvalid Peer sails-auth@1.2.3 wants sails@>0.10.0

**Comment by tjwebb** [comment]
I blame npm. I removed the offending peerDependencies, which were there mostly due to anal-retentiveness anyway.
