### ISSUE TITLE
Cannot set property '_modelCache' of undefined

### ISSUE THREAD

**Issue by dottodot** [tjwebb/sails-permissions#76]
After updating to the latest version I had to manually add the Criteria model file but now I'm getting the following error.

```
error: TypeError: Cannot set property '_modelCache' of undefined
    at Object.require.createModels.bind.then.then.roles (/candb/node_modules/sails-permissions/api/hooks/sails-permissions.js:64:52)
    at Object.tryCatcher (/candb/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/candb/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/candb/node_modules/bluebird/js/main/promise.js:530:18)
    at Async._drainQueue (/candb/node_modules/bluebird/js/main/async.js:182:12)
    at Async._drainQueues (/candb/node_modules/bluebird/js/main/async.js:187:10)
    at Async.drainQueues (/candb/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickDomainCallback (node.js:492:13) [TypeError: Cannot set property '_modelCache' of undefined]
```

**Comment by dottodot** [comment]
OK just tried on a clean app with no issues, so any suggestions as to what's causing this so I can fix it

**Comment by dottodot** [comment]
OK looks like it need to be sails v11 to work properly

**Comment by tjwebb** [comment]
Ah, yes. Unfortunately npm decided to [get pedantic about peerDependencies](https://github.com/npm/npm/issues/6565) so I removed the sails requirement from package.json. The latest version of sails-permissions does require sails 0.11

**Comment by GuillaumeLeclerc** [comment]
I have sails version 11.2 and still have the error

**Comment by refactorized** [comment]
Requires 0.11 or requires 0.11+  ?

**Comment by khchan** [comment]
@tjwebb I was under the impression that sails-permission@2.1.11 and sails-auth@2.1.1 both depend on sails@0.12.0-rc3 since marlinspike is required.  What are the recommended versions for everything then if this isn't the case?

**Comment by andrasi** [comment]
I still have this error after tryting to follow the tutorial from [here](https://github.com/tjwebb/sails-permissions#install)
My package.json looks like this
```json
"dependencies": {
    "bcryptjs": "^2.3.0",
    "ejs": "~0.8.4",
    "grunt": "0.4.2",
    "grunt-contrib-clean": "~0.5.0",
    "grunt-contrib-coffee": "~0.10.1",
    "grunt-contrib-concat": "~0.3.0",
    "grunt-contrib-copy": "~0.5.0",
    "grunt-contrib-cssmin": "~0.9.0",
    "grunt-contrib-jst": "~0.6.0",
    "grunt-contrib-less": "0.11.1",
    "grunt-contrib-uglify": "~0.4.0",
    "grunt-contrib-watch": "~0.5.3",
    "grunt-sails-linker": "~0.9.5",
    "grunt-sync": "~0.0.4",
    "include-all": "~0.1.3",
    "lodash": "^3.10.1",
    "passport": "^0.3.2",
    "passport-facebook": "^2.0.0",
    "passport-google-oauth": "^0.2.0",
    "passport-http-bearer": "^1.0.1",
    "passport-local": "^1.0.0",
    "rc": "~0.5.0",
    "sails": "~0.11.3",
    "sails-auth": "~2.1.1",
    "sails-disk": "~0.10.0",
    "sails-generate-auth": "^0.3.1",
    "sails-permissions": "~2.1.11",
    "suncalc": "^1.7.0",
    "validator": "^4.4.0"
  }
```
```shell
$ node -v
v4.2.3
```
[Here's the complete log](http://pastebin.com/4CqDw6DF)

Thanks

**Comment by khchan** [comment]
@andrasi I was able to get it working with sails-permissions@2.1.11, sails-auth@2.1.1, and sails@0.12.0-rc3.  Also to fix this _modelCache issue I had to create a `config/installedHooks.js` file containing:

**Comment by andrasi** [comment]
Ok, I'll give it a try. For the moment I've got it running by downgrading both sails-permissions and sails-auth.

**Comment by yadavji83** [comment]
@khchan  ur solution removed the error: TypeError: Cannot set property '_modelCache' of undefined

but now this error is coming: error: TypeError: Cannot set property 'protocols' of undefined

**Comment by iolufemi** [comment]
@khchan Your solution worked for me. Thanks
