### ISSUE TITLE
Rename model to controller

### ISSUE THREAD

**Issue by servel333** [tjwebb/sails-permissions#79]
I would like to propose renaming the "model" stuff to "controller". The reason for this is because if you look at [config/fixtures/model.js](https://github.com/tjwebb/sails-permissions/blob/v1.2.1/config/fixtures/model.js#L10), it's not loading the Sails models but instead loading the Sails controllers.

"Model" is a confusing and inaccurate name for this.

**Comment by dapriett** [comment]
I also noticed the hook is comparing the Model (controllers) count to the count of sails.model: https://github.com/tjwebb/sails-permissions/blob/v1.2.1/api/hooks/sails-permissions.js#L37

If we have models with no controller it won't match up.  Also may want the fixtures to do some cleanup if models no longer exist (also throwing off the count).

**Comment by servel333** [comment]
I misread this code, it looks like it is in fact storing the model information and not the controller information, but it's confusing since the way this is written, there must be a controller for the model for the model record to get created and if there is no model record for the model/controller, there's no way to map the actions to permissions.

There are probably some other issues around this, but for now the notion of renaming "model" to "controller" is not really appropriate.
