### ISSUE TITLE
AuditPolicy/RequestLog stores nothing because sails.getHost() returns undefined

### ISSUE THREAD

**Issue by khchan** [tjwebb/sails-permissions#81]
Sails.prototype.getHost will return undefined if host is not explicity set, so when I start up a new sails-permissions application, nothing is stored in requestlog due to the url being invalid.

In AuditPolicy.js, the function should include an or clause for cases like this:

```
function sanitizeRequestUrl (req) {
  var requestUrl = url.format({
    protocol: req.protocol,
    host: sails.getHost() || req.host,
    pathname: req.originalUrl || req.url,
    query: req.query
  });

  return requestUrl.replace(/(password=).*?(&|$)/ig, '$1<hidden>$2');
}
```

**Comment by tjwebb** [comment]
@dbkaplun didn't you alter the `host` logic at some point? Do you have any thoughts on this?

**Comment by dbkaplun** [comment]
Hmm, I think @khchan's suggestion seems valid. It used to be `req.get('host')` but websocket connections don't have a `.get` method so I changed it, but maybe they'll have a `.host`. I think it should be `req.host || sails.getHost()` instead though, so `req`'s host has priority over `getHost()`.

**Comment by tjwebb** [comment]
Ok. A PR would be awesome from whoever wants to fix this. Thanks
