### ISSUE TITLE
Error in sails-permissions hook with sails-mysql

### ISSUE THREAD

**Issue by khchan** [tjwebb/sails-permissions#89]
[Installed: sails@0.11.0, sails-mysql@0.11.0, sails-auth@1.3.1, sails-permissions@1.3.1]

Starting from a new sails app with the latest version of sails-permissions, after lifting with an empty DB, the following error occurs during the User.register step in the user fixture, resulting in the passport and permission tables being empty.  (This behaviour does not occur with sails-mongo)

```
$ sails lift

info: Starting app...

info: permissions: initializing sails-permissions hook
debug: sails-permissions: syncing waterline models\
debug: sails-permissions: admin user does not exist; creating...
debug: [ { type: 'insert',
    collection: 'role_users__user_roles',
    criteria: { role_users: 2, user_roles: 1 },
    values: { role_users: 2, user_roles: 1 },
    err: [Error: Trying to '.add()' an instance which already exists!] } ]
error: [ { type: 'insert',
    collection: 'role_users__user_roles',
    criteria: { role_users: 2, user_roles: 1 },
    values: { role_users: 2, user_roles: 1 },
    err: [Error: Trying to '.add()' an instance which already exists!] } ]
```

**Comment by tjwebb** [comment]
Try upgrading sails-permissions to 1.3.1.

**Comment by khchan** [comment]
@tjwebb I've upgraded to 1.3.1, still same issue...

**Comment by tjwebb** [comment]
What version of sails are you running?

**Comment by khchan** [comment]
0.11.0

**Comment by ftechz** [comment]
I had the same issue. The problem was that it tried to look for the column 'createdBy' which doesn't exist in the junction tables.

I've submitted a pull request for the fix: https://github.com/tjwebb/sails-permissions/pull/94

**Comment by khchan** [comment]
Thanks @ftechz this PR fixes my issue.

**Comment by justusbluemer** [comment]
Thank you for reporting this bug, I just spent a couple of hours trying to track down the source of the problem.
I hope the change makes it into the package soon.

**Comment by BLamy** [comment]
That PR worked great thanks.
