### ISSUE TITLE
Would just love to know where to set the environment variables mentioned in the README

### ISSUE THREAD

**Issue by binchem** [tjwebb/sails-permissions#92]
Would just love to know where to set the environment variables mentioned in the README

**Comment by khchan** [comment]
You can set them directly via terminal:
```
export ADMIN_USERNAME=admin
export ADMIN_EMAIL=admin@example.com
export ADMIN_PASSWORD=admin1234
```
Or set the variables in a config file:
```
sails.config.permissions.adminUsername = 'admin'
sails.config.permissions.adminEmail = 'admin@example.com'
sails.config.permissions.adminPassword = 'admin1234'
```

**Comment by Benew** [comment]
Thanks a lot. Just missed the permissions object in the local.js declaration.
Close #92

**Comment by dustmoo** [comment]
Is it just me? Or in sails 0.11.2 is the permission object missing from local.js? Refactored out to its own permissions.js config file? Exporting these vars is fine. But sails.config doesn't work in ANY of the config *.js files that I can tell.

**Comment by adamwlarson** [comment]
I wanted to add to what @dustmoo is saying, it does appear it has been factored out and it doesn't appear that sails.config does work in anything. Is there an update on where the variables should be set?
