### ISSUE TITLE
Can someone help me with a working sample?

### ISSUE THREAD

**Issue by fuzzball1980** [tjwebb/sails-permissions#98]
I'm just starting with sails and sails-permission and I can't make it work. All the commands in the Quickstart page runs well, but for some reason no Models/Controllers/Policies are created. I have tried in my Windows 8 laptop and in a ubuntu server from scratch.

Do I need to copy/paste the models/controllers/policies by hand?

Thanks!

**Comment by ryanwilliamquinn** [comment]
You don't need to copy/paste the models/controllers/policies by hand.

I have a rough draft of an example project walkthrough here: http://threeninetyfive.net/blog/2015/07/14/sails-permissions-by-example/

Any feedback is welcome.

**Comment by fuzzball1980** [comment]
thank you I will try it!

**Comment by fuzzball1980** [comment]
OK, I have followed the steps one by one but nothing, for some reason the models/controllers/policies are no created in my dev environment.

I just see a dependency version warn.

The same happens in a fresh ubuntu server installation. I'm pretty lost here!

D:\Test\reviews>npm install --save lodash
lodash@3.10.0 node_modules\lodash

D:\Test\reviews>npm install --save sails-permissions
npm WARN peerDependencies The peer dependency sails-auth@>=1.2.7 included from s
ails-permissions will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD
ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it
explicitly.
sails-auth@1.3.1 node_modules\sails-auth
├── passport-facebook@1.0.3 (passport-oauth2@1.1.2)
├── passport-twitter@1.0.3 (xtraverse@0.1.0, passport-oauth1@1.0.1)
└── passport-google-oauth@0.2.0 (pkginfo@0.3.0, passport-oauth@1.0.0)

sails-permissions@1.2.2 node_modules\sails-permissions
├── pluralize@1.1.2
├── sails-generate-entities@0.11.4
├── fnv-plus@1.2.12
├── bluebird@2.9.34
├── waterline-criteria@0.11.1 (lodash@2.4.2)
└── sails-auth@1.3.1 (passport-facebook@1.0.3, passport-twitter@1.0.3, passport-
google-oauth@0.2.0)

D:\Test\reviews>sails generate permissions-api
info: Created a new permissions-api!

D:\Test\reviews>sails generate api review
info: Created a new api!

D:\Test\reviews>

D:\Test\reviews\api\models>dir
 Volume in drive D is Data
 Volume Serial Number is 0468-22D0

 Directory of D:\Test\reviews\api\models

26/07/2015  09:23 p.m.    <DIR>          .
26/07/2015  09:23 p.m.    <DIR>          ..
26/07/2015  09:19 p.m.                 0 .gitkeep
26/07/2015  09:23 p.m.               236 Review.js
               2 File(s)            236 bytes
               2 Dir(s)  246.408.904.704 bytes free

**Comment by ryanwilliamquinn** [comment]
I'm seeing a similar problem, checking it out now.

**Comment by ryanwilliamquinn** [comment]
It looks like we have to update the .sailsrc in my example, so it looks like this now (adding '/generator'), and then re-run `sails generate permissions-api`:
```{
  "generators": {
    "modules": {
      "permissions-api": "sails-permissions/generator"
    }
  }
}```

**Comment by fuzzball1980** [comment]
I got the following error after adding /generator like shows in the Quickstarted documentation


error: Error in "permissions-api" generator (loaded from sails-permissions/gener
ator)
C:\Users\cesar\AppData\Roaming\npm\node_modules\sails\node_modules\sails-generat
e\lib\index.js:51
      throw e;
            ^
Error: Cannot find module 'D:\Test\reviews\sails-permissions\generator'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (C:\Users\cesar\AppData\Roaming\npm\node_modules\sails\nod
e_modules\sails-generate\lib\index.js:71:19)
    at Command.module.exports (C:\Users\cesar\AppData\Roaming\npm\node_modules\s
ails\bin\sails-generate.js:104:10)
    at Command.<anonymous> (C:\Users\cesar\AppData\Roaming\npm\node_modules\sail
s\node_modules\commander\index.js:249:8)
    at Command.emit (events.js:110:17)
    at Command.parseArgs (C:\Users\cesar\AppData\Roaming\npm\node_modules\sails\
node_modules\commander\index.js:477:12)
    at Command.parse (C:\Users\cesar\AppData\Roaming\npm\node_modules\sails\node
_modules\commander\index.js:370:21)

**Comment by ryanwilliamquinn** [comment]
Could you update the sails-permissions version in package.json to 1.3.3, we just published a new version.

**Comment by fuzzball1980** [comment]
should I run any command after the update?

**Comment by fuzzball1980** [comment]
I have updated with version 1.3.3 and run npm install --save sails-permissions again
but I get the same error. IF I change { "generators": { "modules": { "permissions-api": "sails-permissions/generator" } } } back to "permissions-api": "sails-permissions" the error is gone but no files are created

**Comment by ryanwilliamquinn** [comment]
Okay I will try it on my windows box and see if anything changes.

**Comment by fuzzball1980** [comment]
OK, thanks for your help!!

**Comment by ryanwilliamquinn** [comment]
I get the same error on windows.  Are you able to try it on ubuntu still?  It is working fine for me on osx.  I will keep troubleshooting the windows version.

**Comment by fuzzball1980** [comment]
Yes, and I got the same error on ubuntu server 14.10 installing from scratch

**Comment by fuzzball1980** [comment]
@ryanwilliamquinn I have run this quickstart (http://theambitious.com/index.php/2015/07/26/sailsjs-sails-permissions-on-linux-quick-start/) in ubuntu and I got the files created!

**Comment by ryanwilliamquinn** [comment]
Great, I will check it out.

**Comment by ryanwilliamquinn** [comment]
Well, I was able to replicate it on windows for a little while, then I deleted the node modules and reinstalled, and it all started working.  Nothing really changed, wish I knew more.  I don't do much node stuff on windows, sorry I can't help more.

**Comment by fuzzball1980** [comment]
I will keep digging on it. Thank you!

**Comment by ryanwilliamquinn** [comment]
@fuzzball1980 Could you try cloning this project, checking out the branch named 'complete', npm installing and running it?  
https://github.com/ryanwilliamquinn/sails-permissions-example
I'm curious if that will work on your windows box.

**Comment by fuzzball1980** [comment]
@ryanwilliamquinn  it works! any conclusion?

**Comment by fuzzball1980** [comment]
If I try to run sails generate permission-api I got the following error

D:\Users\Cesar\Documents\GitHub\sails-permissions-example>sails generate permiss
ions-api
error: Error in "permissions-api" generator (loaded from sails-permissions/gener
ator)
C:\Users\cesar\AppData\Roaming\npm\node_modules\sails\node_modules\sails-generat
e\lib\index.js:51
      throw e;
            ^
Error: Cannot find module 'D:\Users\Cesar\Documents\GitHub\sails-permissions-exa
mple\sails-permissions\generator'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (C:\Users\cesar\AppData\Roaming\npm\node_modules\sails\nod
e_modules\sails-generate\lib\index.js:71:19)
    at Command.module.exports (C:\Users\cesar\AppData\Roaming\npm\node_modules\s
ails\bin\sails-generate.js:104:10)
    at Command.<anonymous> (C:\Users\cesar\AppData\Roaming\npm\node_modules\sail
s\node_modules\commander\index.js:249:8)
    at Command.emit (events.js:110:17)
    at Command.parseArgs (C:\Users\cesar\AppData\Roaming\npm\node_modules\sails\
node_modules\commander\index.js:477:12)
    at Command.parse (C:\Users\cesar\AppData\Roaming\npm\node_modules\sails\node
_modules\commander\index.js:370:21)

D:\Users\Cesar\Documents\GitHub\sails-permissions-example>

**Comment by fuzzball1980** [comment]
@ryanwilliamquinn have you changed anything on that project? I 'm still unable to install sails-permissions on windows :-(

**Comment by ryanwilliamquinn** [comment]
@fuzzball1980 did you ever find a solution to your windows issue?  I am going to close this issue, since there are a couple working examples now.

**Comment by 1ewallace1** [comment]
I was getting that same windows issue.

I changed .sailsrc to:
```
{
  "generators": {
    "modules": {
		"permissions-api": "node_modules/sails-permissions/generator"
	}
  }
}
```

Emphasis on the **node_modules/**

Hope that helps.

**Comment by sz06** [comment]
@1ewallace1 That worked for me. I don't see any error now but unfortunately files are not created :(
